# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6992a91d102887c08d21044c401a6b6b09230373f4a0b0bf174454354bb646c658cffe0658fd78fe85fa5d5f24bbd25327e0c9f51f83bfaa422dd9bff0f0a53f

test:
  secret_key_base: 26a30559b93d0a42091e37cbe3c4c201ff9384049fc7af70d5da23fa27b4c7d2413cd8564082dddf77fe64c64fcebec669e482bbd8ad944037a6653deb5d7abb

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
